version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.Extensions.Configuration.AzureKeyVault
    versions:
    - 3.1.11
    - 3.1.12
    - 3.1.13
  - dependency-name: Microsoft.Extensions.Identity.Core
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.SpaServices.Extensions
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
  - dependency-name: Microsoft.ApplicationInsights.AspNetCore
    versions:
    - 2.16.0
